name: Get Repo Information

permissions: read-all

on: workflow_dispatch

jobs:
  echo-information:
    runs-on: ubuntu-22.04
    steps:
      - run: touch issues_info.json >> gh issue status --json
      - run: cat issues_info.json
    env: 
      GH_TOKEN: ${{ github.token }}
      GH_REPO: ${{ github.repository }}
