name: Get Repo Information

permissions: write-all

on: 
  workflow_dispatch:
  schedule:
    - cron: "0 12 * * 5"

jobs:
  echo-information:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      
      # Create payload
      - run : gh issue list --json author,title,body,labels,id,createdAt,closedAt,state,milestone,assignees,url >> .github/workflow-utilities/issues.json
      - run : gh pr list --json author,baseRefName,body,changedFiles,createdAt,files,headRefName,labels,mergeable,mergedAt,milestone,state,title,url >> .github/workflow-utilities/pull_request.json
      - run : git ls-remote --heads origin >> .github/workflow-utilities/branches.txt
      
      # Generate report
      - run: python3 .github/workflow-utilities/github-payload-formatter.py
      
      # Update issue 
      - run : gh issue edit 16 --title="Weekly Report" --body=$"`cat report.md`"
    
    env: 
      GH_TOKEN: ${{ github.token }}
      GH_REPO: ${{ github.repository }}
