name: weekly updater

#TODO: Add schedule when workflow is tested and works
on: workflow_dispatch

jobs:
  check-all-branches:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - run: echo {gh.repository}
