name: Get Repo Information

on: workflow_dispatch

jobs:
  echo-information:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - run: gh issues list
      - run: gh pr list
      - run: gh release list

    env: 
      GH_TOKEN: ${{ github.token }}
      GH_REPO: ${{ github.repository }}
